# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BSProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BSProject
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'pop'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'DACircularProgress'
    pod 'SVProgressHUD'
    pod 'RXCollections'
  # 友盟分享
    # U-Share SDK UI模块（分享面板，建议添加）
    pod ‘UMengUShare/UI’
    # 集成微信(完整版14.4M)
    pod ‘UMengUShare/Social/WeChat'
    # 集成新浪微博(完整版25.3M)
    pod ‘UMengUShare/Social/Sina'
end
